imports:
    - { resource: repositories.yml }
    - { resource: managers.yml }

services:
    app.form.registration:
        class: ApiBundle\Form\RegistrationType
        tags:
            - { name: form.type }
